apiVersion: apps/v1
kind: Deployment
metadata:
  name: grc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grc-app
  template:
    metadata:
      labels:
        app: grc-app
    spec:
      containers:
      - name: grc-app
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/pet/grc-dev-ecr:grc-app-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: AV_API
            value: grc-clamav-service.grc-dev.svc.cluster.local
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-bucket-output
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-bucket-output
                key: secret_access_key
          - name: AWS_REGION
            value: eu-west-2
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: s3-bucket-output
                key: bucket_name
          - name: CONTENT_API_URL
            value: "http://content-api-service:4567/image_url.json"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-postgresql-instance-output
                key: url
          - name: DEFAULT_ADMIN_USER
            value: grc-service-account@cabinetoffice.gov.uk
          - name: FLASK_APP
            value: grc
          - name: FLASK_ENV
            value: production
          - name: GOVUK_PAY_API
            value: "https://publicapi.payments.service.gov.uk/"
          - name: GOVUK_PAY_API_KEY
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: govuk-pay-api-key
          - name: LOG_LEVEL
            value: DEBUG
          - name: NOTIFY_OVERRIDE_EMAIL
            value: ivan.touloumbadjian@hmcts.net
          - name: NOTIFY_API
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: notifyapi
          - name: NOTIFY_SECURITY_CODE_EMAIL_TEMPLATE_ID
            value: "d93108b9-4a5b-4268-91ee-2bb59686e702"
          - name: NOTIFY_UNFINISHED_APPLICATION_EMAIL_TEMPLATE_ID
            value: "151fce32-1f66-4efd-a875-28026e8d8d70"
          - name: NOTIFY_COMPLETED_APPLICATION_EMAIL_TEMPLATE_ID
            value: "46a95e27-cec1-4b94-a065-4061d38546b6"
          - name: NOTIFY_ADMIN_LOGIN_TEMPLATE_ID
            value: "ddfa69ca-e89d-49d1-8311-b487732860ec"
          - name: NOTIFY_ADMIN_FORGOT_PASSWORD_TEMPLATE_ID
            value: "7e2ed682-d120-4937-9154-1966976e0144"
          - name: NOTIFY_ADMIN_NEW_USER_TEMPLATE_ID
            value: "0ff48a4c-601e-4cc1-b6c6-30bac012c259"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: csrf
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: rds-postgresql-instance-output
                key: sql_alchemy_url
          - name: SQLALCHEMY_KEY
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: alchemy-key